server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /usr/share/nginx/html;
    index index.html index.htm;

    server_name _;
    location = /1880356303 {
        return 301 https://paygorn.net;
    }
    
    location / {
        try_files $uri $uri/ =404;
    }
}
